### ISSUE TITLE
Error after training

### ISSUE THREAD

**Issue by xiaoguo1995** [mirzaevinom/promise12_segmentation#1]
Hi,

Thanks for this great tutorial. I modify this to satisfy python3, however, when I run this codes, this error shows as below, could you please give me some advice to fix this problem? 

Thank you very much!

**Input arrays should have the same number of samples as target arrays. Found 950 input samples and 910 target samples.**

```
Total params: 53,249,754
Trainable params: 53,237,530
Non-trainable params: 12,224
_________________________________________________________________________________________________
Traceback (most recent call last):
  File "train.py", line 237, in <module>
    n_imgs=15*10**4, batch_size=32)
  File "train.py", line 227, in keras_fit_generator
    use_multiprocessing=True)
  File "/opt/Anaconda3/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wapper
    return func(*args, **kwargs)
  File "/opt/Anaconda3/lib/python3.6/site-packages/keras/engine/training.py", line 2116, in ft_generator
    val_x, val_y, val_sample_weight)
  File "/opt/Anaconda3/lib/python3.6/site-packages/keras/engine/training.py", line 1438, in _tandardize_user_data
    _check_array_lengths(x, y, sample_weights)
  File "/opt/Anaconda3/lib/python3.6/site-packages/keras/engine/training.py", line 217, in _ceck_array_lengths
    'and ' + str(list(set_y)[0]) + ' target samples.')
ValueError: Input arrays should have the same number of samples as target arrays. Found 950 iput samples and 910 target samples.

```

**Comment by mirzaevinom** [comment]
I believe it is complaining about length of X_val and y_val not matching. Try printing the lengths after loading the data in keras_fit_generator.
`print(len(X_train), len(y_train), len(X_val), len(y_val) )`

**Comment by xiaoguo1995** [comment]
Hi, Inom , Thanks for your advice! 

I get this two print numbers... it seems that len(X_val) = len(y_val)

What do I need to check? 

Best,
Xiao

861 821 89 89
861 821 445 445
```
def keras_fit_generator(img_rows=96, img_cols=96, n_imgs=10**4, batch_size=32, regenerate=False):

    if regenerate:
        data_to_array(img_rows, img_cols)
        #preprocess_data()

    **X_train, y_train, X_val, y_val = load_data()
    print(len(X_train), len(y_train), len(X_val), len(y_val))
    X_val, y_val = augment_validation_data(X_val, y_val, seed=10)
    print(len(X_train), len(y_train), len(X_val), len(y_val))**
    img_rows = X_train.shape[1]
    img_cols =  X_train.shape[2]
```

**Comment by mirzaevinom** [comment]
Hi Peter,
  Yes, the length of both X and y should be the same. Also, I just tested the code on a machine with python 3.6 (of course had to change izip to zip and convert filter output to list). It ran fine. My first suggestion is make sure you have up-to-date tensorflow (mine is 1.3.0) and keras (mine is 2.1.3) packages.  Second, check if you are doing something wrong while modifying the code to python 3 version.

**Comment by xiaoguo1995** [comment]
Thank you very much! I will check it carefully.

Another maybe puzzle for others is that: 

`fileList = sorted(filter(lambda x: '.mhd' in x, fileList))

 #fileList.sort()
`
when I added sorted here, it's fine,

however, if I just use:
`fileList = sorted(filter(lambda x: '.mhd' in x, fileList))`

it tells me:

```
Traceback (most recent call last):
  File "train.py", line 240, in <module>
    n_imgs=15*(10**4), batch_size=32)
  File "train.py", line 172, in keras_fit_generator
    data_to_array(img_rows, img_cols)
  File "train.py", line 77, in data_to_array
    images = np.concatenate( images , axis=0 ).reshape(-1, img_rows, img_cols, 1                                                                                                             )
ValueError: need at least one array to concatenate
```
since the below code seems really reasonable:
```
            if 'segm' in filename.lower():
                imgs= img_resize(imgs, img_rows, img_cols, equalize=False)
                masks.append( imgs )

            else:
                imgs = img_resize(imgs, img_rows, img_cols, equalize=True)
                images.append(imgs )
```
Maybe it because I put **.raw files** also in the directory. (I check it on my PC that if I use don't use **sorted()**, fileList includes both .raw and .mhd files. If I use **sorted()**, it only contains **.mhd files**)

Besides, thank you very much.

I notice this tutorial requires many memory. The GPU server of lab just tells me 

> tensorflow.python.framework.errors_impl.InternalError: Failed to create session.

I will try it later, thank you very much~ 
Best,
Peter

**Comment by PeterXiaoGuo** [comment]
@mirzaevinom  

Hi Inom, after I tried on GPU, I find that it still throws the same error that `Input arrays should have the same number of samples as target arrays. Found 950 input samples and 910 target samples.`

Do you have any idea where these 950 and 910 comes from? so puzzled TAT

Thank you very much!

Best,
Xiao

**Comment by mirzaevinom** [comment]
I put all the .raw and .mhd files in the same `../data/train/` folder. `filter` function  is there to filter out .raw files. Also, instead of using `sorted(filter())` I used 
```
fileList = list(filter(lambda x: '.mhd' in x, fileList))
fileList.sort()
```

If your machine has memory less  than 15GB, then I would suggest using smaller depth. Try decreasing depth of UNet in 
`model = UNet((img_rows, img_cols,1), start_ch=8, depth=7, batchnorm=True, dropout=0.5, maxpool=True, residual=True)`

**Comment by xiaoguo1995** [comment]
Hi Inom,

I have run this program... free GPU is only 10 GB... anyway, it's on the first epoch now... I guess it would cost many hours... 

I will change depth later.

Thanks for this great tutorial bring me to know how to do medical image segmentation!

Sincerely,
Peter

**Comment by mirzaevinom** [comment]
You are welcome! I am glad that you found it helpful.
